[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015ABA9A3E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a26231928737c2d3342168099ea5c81c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015ABA9A3DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a26231928737c2d3342168099ea5c81c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015ABA9A3520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a26231928737c2d3342168099ea5c81c