[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200A562BFA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fcd1c9f9faea04c9dc05c34e70dea256
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200A562B670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fcd1c9f9faea04c9dc05c34e70dea256
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200A562BF70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fcd1c9f9faea04c9dc05c34e70dea256