[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019760473280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0277e25e5f74b1fc48801eba3489991a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197604736A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0277e25e5f74b1fc48801eba3489991a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019760473B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0277e25e5f74b1fc48801eba3489991a